/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beebook_app.form;

import beebook_app.Beebook_App;
import beebook_app.controller.AnggotaController;
import beebook_app.controller.PeminjamanController;
import beebook_app.controller.PengembalianController;
import beebook_app.data.Peminjaman;
import beebook_app.data.Pengembalian;
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Annisa Juraini
 */
public class FormPengembalian extends javax.swing.JInternalFrame {
    Peminjaman pj=new Peminjaman();
    Pengembalian pb=new Pengembalian();
    PeminjamanController pCont=new PeminjamanController(Beebook_App.emf);
    PengembalianController pbCont=new PengembalianController(Beebook_App.emf);
    AnggotaController aCont=new AnggotaController(Beebook_App.emf);
    DefaultTableModel model;
    Date kembali;
    Date dikembalikan;
    double harga;
    String idAnggota;
    /**
     * Creates new form FormPengembalian
     */
    public FormPengembalian(String noPinjam, String idAnggota) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(null);
        tampilPinjam(noPinjam);
        tampilBuku(noPinjam);
        denda();
        this.idAnggota=idAnggota;
    }
    
    private void tampilPinjam(String noPinjam){
        pj=pCont.findPinjam(noPinjam);
        txtNo.setText(noPinjam);
        SimpleDateFormat sdf=new SimpleDateFormat("dd MMMM yyyy", Locale.forLanguageTag("in-ID"));
        txtTglPinjam.setText(sdf.format(pj.getTglPinjam()));
        txtKembali.setText(sdf.format(pj.getTglPengembalian()));
        txtHariIni.setText(sdf.format(new Date()));
        txtBiaya.setText(String.valueOf(pj.getBiayaSewa()));
    }
    
    private void tampilBuku(String noPinjam){
        model=new DefaultTableModel();
        model.addColumn("ID Buku");
        model.addColumn("Judul");
        model.addColumn("Pengarang");
        model.addColumn("Kategori");
        model.addColumn("Harga");
        tableBuku.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tableBuku.setModel(pbCont.showTableKembali(model, noPinjam));
        tableBuku.getColumnModel().getColumn(1).setCellRenderer(new TableWrap());
    }
    
    private void denda(){
        SimpleDateFormat sdf=new SimpleDateFormat("dd MMMM yyyy", Locale.forLanguageTag("id-ID"));
        try{
            kembali= sdf.parse(txtKembali.getText());
            dikembalikan= new Date();
        }catch(Exception ex){
            ex.printStackTrace();
        }
        int x=dikembalikan.compareTo(kembali);
        if(x>0){
            int selisih=dikembalikan.getDate()-kembali.getDate();
            harga=2000*selisih;
            txtDenda.setForeground(Color.red);
            txtDenda.setText(String.valueOf(harga));
        }else{
            harga=0;
            txtDenda.setText(String.valueOf(harga));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelNama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        panelPinjam = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBuku = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTglPinjam = new javax.swing.JTextField();
        txtNo = new javax.swing.JTextField();
        txtKembali = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtBiaya = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDenda = new javax.swing.JTextField();
        txtHariIni = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnKembalii = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.CardLayout());

        panelUtama.setBackground(new java.awt.Color(255, 255, 255));

        panelNama.setBackground(new java.awt.Color(255, 97, 150));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pengembalian");

        javax.swing.GroupLayout panelNamaLayout = new javax.swing.GroupLayout(panelNama);
        panelNama.setLayout(panelNamaLayout);
        panelNamaLayout.setHorizontalGroup(
            panelNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNamaLayout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(436, 436, 436))
        );
        panelNamaLayout.setVerticalGroup(
            panelNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        panelInfo.setLayout(new java.awt.CardLayout());

        panelPinjam.setBackground(new java.awt.Color(255, 255, 255));
        panelPinjam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelPinjam.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 940, 10));

        tableBuku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableBuku.setForeground(new java.awt.Color(51, 51, 51));
        tableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Buku", "Judul", "Pengarang", "Kategori", "Harga"
            }
        ));
        tableBuku.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tableBuku.setRowHeight(20);
        tableBuku.setRowMargin(2);
        tableBuku.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tableBuku);

        panelPinjam.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 780, 180));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("No. Pinjaman");
        panelPinjam.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, 120, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Tgl Peminjaman");
        panelPinjam.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 20));

        txtTglPinjam.setEditable(false);
        txtTglPinjam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelPinjam.add(txtTglPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 200, -1));

        txtNo.setEditable(false);
        txtNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelPinjam.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 200, -1));

        txtKembali.setEditable(false);
        txtKembali.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelPinjam.add(txtKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 200, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Tgl Pengembalian");
        panelPinjam.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Biaya Sewa");
        panelPinjam.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 90, 20));

        txtBiaya.setEditable(false);
        txtBiaya.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelPinjam.add(txtBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 200, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Denda");
        panelPinjam.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 90, 20));

        txtDenda.setEditable(false);
        txtDenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelPinjam.add(txtDenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 200, -1));

        txtHariIni.setEditable(false);
        txtHariIni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelPinjam.add(txtHariIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 200, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Tgl Hari ini");
        panelPinjam.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 90, 20));

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Check File_25px.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        panelPinjam.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 170, -1));

        btnKembalii.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKembalii.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Return_25px.png"))); // NOI18N
        btnKembalii.setText("Batal");
        btnKembalii.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKembalii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliiActionPerformed(evt);
            }
        });
        panelPinjam.add(btnKembalii, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 190, -1));

        panelInfo.add(panelPinjam, "card3");

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))
        );

        getContentPane().add(panelUtama, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliiActionPerformed
        FormTransaksi FT=new FormTransaksi();
        JDesktopPane pane=getDesktopPane();
        pane.add(FT);
        FT.setVisible(true);
    }//GEN-LAST:event_btnKembaliiActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        pb.setNoPinjam(txtNo.getText());
        pb.setTglDikembalikan(new Date());
        pb.setDenda(Double.parseDouble(txtDenda.getText()));
        pCont.Status(txtNo.getText(), "Selesai");
        aCont.Status(idAnggota, "-");
        try{
            pbCont.save(pb);
        }catch(Exception ex){
            ex.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        FormTransaksi FT=new FormTransaksi();
        JDesktopPane dp=getDesktopPane();
        dp.add(FT);
        FT.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembalii;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelNama;
    private javax.swing.JPanel panelPinjam;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTable tableBuku;
    private javax.swing.JTextField txtBiaya;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtHariIni;
    private javax.swing.JTextField txtKembali;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtTglPinjam;
    // End of variables declaration//GEN-END:variables
}
