/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beebook_app.form;

import beebook_app.Beebook_App;
import beebook_app.controller.AnggotaController;
import beebook_app.controller.DetailController;
import beebook_app.controller.PeminjamanController;
import beebook_app.controller.PengembalianController;
import beebook_app.data.Anggota;
import beebook_app.data.Peminjaman;
import beebook_app.data.Pengembalian;
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Annisa Juraini
 */
public class FormDetail extends javax.swing.JInternalFrame {
    Peminjaman pj=new Peminjaman();
    Anggota ag=new Anggota();
    Pengembalian pb=new Pengembalian();
    PeminjamanController pCont=new PeminjamanController(Beebook_App.emf);
    AnggotaController aCont=new AnggotaController(Beebook_App.emf);
    DetailController dCont=new DetailController(Beebook_App.emf);
    PengembalianController pbCont=new PengembalianController(Beebook_App.emf);
    DefaultTableModel model;
    String noPinjam, idAnggota;
    Date kembali;
    Date dikembalikan;
    double harga;
    /**
     * Creates new form FormDetail
     */
    public FormDetail(String noPinjam, String idAnggota) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(null);
        this.noPinjam=noPinjam;
        this.idAnggota=idAnggota;
        validasiStatus();
    }
    
    private void validasiStatus(){
        pj=pCont.findPinjam(noPinjam);
        if(pj.getStatus().equals("Selesai")){
            labelHari.setText("Dikembalikan");
            btnPengembalian.setEnabled(false);
            int id=pbCont.id(noPinjam);
            pb=pbCont.findPengembalian(id);
            SimpleDateFormat sdf=new SimpleDateFormat("dd MMMM yyyy", Locale.forLanguageTag("id-ID"));
            tampilPinjam(noPinjam);
            tampilAnggota(idAnggota);
            tampilBuku(noPinjam);
            txtHariIni.setText(sdf.format(pb.getTglDikembalikan()));
            txtDenda.setText(String.valueOf(pb.getDenda()));
        }else{
            labelHari.setText("Tgl Hari Ini");
            btnPengembalian.setEnabled(true);
            tampilPinjam(noPinjam);
            tampilAnggota(idAnggota);
            tampilBuku(noPinjam);
            denda();
        }
    }
    
    private void tampilPinjam(String noPinjam){
        txtNo.setText(noPinjam);
        SimpleDateFormat sdf=new SimpleDateFormat("dd MMMM yyyy", Locale.forLanguageTag("in-ID"));
        txtTglPinjam.setText(sdf.format(pj.getTglPinjam()));
        txtKembali.setText(sdf.format(pj.getTglPengembalian()));
        txtHariIni.setText(sdf.format(new Date()));
        txtBiaya.setText(String.valueOf(pj.getBiayaSewa()));
    }
    
    private void tampilAnggota(String idAnggota){
        ag=aCont.findAnggota(idAnggota);
        txtId.setText(ag.getIdAnggota());
        txtNama.setText(ag.getNama());
        txtTelp.setText(ag.getNoTelp());
        txtEmail.setText(ag.getEmail());
        txtAlamat.setText(ag.getAlamat());
    }
    
    private void tampilBuku(String noPinjam){
        model=new DefaultTableModel();
        model.addColumn("ID Buku");
        model.addColumn("Judul");
        model.addColumn("Pengarang");
        model.addColumn("Penerbit");
        model.addColumn("Tahun");
        model.addColumn("Kategori");
        model.addColumn("Harga");
        tableBuku.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tableBuku.setModel(dCont.showTablePinjam(model, noPinjam));
        tableBuku.getColumnModel().getColumn(1).setCellRenderer(new TableWrap());
    }
    
    private void denda(){
        SimpleDateFormat sdf=new SimpleDateFormat("dd MMMM yyyy", Locale.forLanguageTag("id-ID"));
        try{
            kembali= sdf.parse(txtKembali.getText());
            dikembalikan= new Date();
        }catch(Exception ex){
            ex.printStackTrace();
        }
        int x=dikembalikan.compareTo(kembali);
        if(x>0){
            int selisih=dikembalikan.getDate()-kembali.getDate();
            harga=2000*selisih;
            txtDenda.setForeground(Color.red);
            txtDenda.setText(String.valueOf(harga));
        }else{
            harga=0;
            txtDenda.setText(String.valueOf(harga));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelNama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        panelPinjam = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnKembalii = new javax.swing.JButton();
        btnPengembalian = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBuku = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTglPinjam = new javax.swing.JTextField();
        txtNo = new javax.swing.JTextField();
        txtKembali = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtBiaya = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDenda = new javax.swing.JTextField();
        txtHariIni = new javax.swing.JTextField();
        labelHari = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(970, 580));
        getContentPane().setLayout(new java.awt.CardLayout());

        panelUtama.setBackground(new java.awt.Color(255, 255, 255));

        panelNama.setBackground(new java.awt.Color(255, 97, 150));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Detail Peminjaman");

        javax.swing.GroupLayout panelNamaLayout = new javax.swing.GroupLayout(panelNama);
        panelNama.setLayout(panelNamaLayout);
        panelNamaLayout.setHorizontalGroup(
            panelNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNamaLayout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(436, 436, 436))
        );
        panelNamaLayout.setVerticalGroup(
            panelNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        panelInfo.setLayout(new java.awt.CardLayout());

        panelPinjam.setBackground(new java.awt.Color(255, 255, 255));
        panelPinjam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        btnKembalii.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKembalii.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Return_25px.png"))); // NOI18N
        btnKembalii.setText("Kembali");
        btnKembalii.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKembalii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliiActionPerformed(evt);
            }
        });
        jPanel5.add(btnKembalii);

        btnPengembalian.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Return Book_25px.png"))); // NOI18N
        btnPengembalian.setText("Buka Pengembalian");
        btnPengembalian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengembalianActionPerformed(evt);
            }
        });
        jPanel5.add(btnPengembalian);

        panelPinjam.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 370, -1));
        panelPinjam.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 940, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Email");
        panelPinjam.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, 20));

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        panelPinjam.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 340, -1));

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        panelPinjam.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 200, -1));

        txtNama.setEditable(false);
        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        panelPinjam.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 340, -1));

        txtTelp.setEditable(false);
        txtTelp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        panelPinjam.add(txtTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 340, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("ID Anggota");
        panelPinjam.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Nama Anggota");
        panelPinjam.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("No Telpon");
        panelPinjam.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Alamat");
        panelPinjam.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, 20));

        txtAlamat.setColumns(20);
        txtAlamat.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtAlamat.setLineWrap(true);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        panelPinjam.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 250, 100));

        tableBuku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableBuku.setForeground(new java.awt.Color(51, 51, 51));
        tableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Buku", "Judul", "Pengarang", "Penerbit", "Tahun", "Kategori", "Harga"
            }
        ));
        tableBuku.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tableBuku.setRowHeight(20);
        tableBuku.setRowMargin(2);
        tableBuku.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tableBuku);

        panelPinjam.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 920, 180));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("No. Pinjaman");
        panelPinjam.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, 90, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Tgl Peminjaman");
        panelPinjam.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 20));

        txtTglPinjam.setEditable(false);
        txtTglPinjam.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        panelPinjam.add(txtTglPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 200, -1));

        txtNo.setEditable(false);
        txtNo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        panelPinjam.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 200, -1));

        txtKembali.setEditable(false);
        txtKembali.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        panelPinjam.add(txtKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 200, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Tgl Pengembalian");
        panelPinjam.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Biaya Sewa");
        panelPinjam.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, 20));

        txtBiaya.setEditable(false);
        txtBiaya.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        panelPinjam.add(txtBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 200, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Denda");
        panelPinjam.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, 20));

        txtDenda.setEditable(false);
        txtDenda.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        panelPinjam.add(txtDenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 200, -1));

        txtHariIni.setEditable(false);
        txtHariIni.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        panelPinjam.add(txtHariIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 200, -1));

        labelHari.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelHari.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelHari.setText("Tgl Hari ini");
        panelPinjam.add(labelHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 20));

        panelInfo.add(panelPinjam, "card3");

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelUtama, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliiActionPerformed
        FormTransaksi FT=new FormTransaksi();
        JDesktopPane pane=getDesktopPane();
        pane.add(FT);
        FT.setVisible(true);        
    }//GEN-LAST:event_btnKembaliiActionPerformed

    private void btnPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengembalianActionPerformed
        String a=txtNo.getText();
        String b=txtId.getText();
        FormPengembalian FP=new FormPengembalian(a, b);
        JDesktopPane dp=getDesktopPane();
        dp.add(FP);
        FP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPengembalianActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembalii;
    private javax.swing.JButton btnPengembalian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelHari;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelNama;
    private javax.swing.JPanel panelPinjam;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTable tableBuku;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtBiaya;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHariIni;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtKembali;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtTglPinjam;
    // End of variables declaration//GEN-END:variables

}
