/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beebook_app.form;

import java.awt.Color;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author Annisa Juraini
 */
public class FormUtama extends javax.swing.JFrame {
    int xx;
    int xy;
    
    /**
     * Creates new form NewJFrame
     */
    public FormUtama(String nama) {
        initComponents();
        setLocationRelativeTo(null);
        label.setText(nama);
       
    }
    
    private void setColor(JPanel panel){
        panel.setBackground(new Color(255,201,201));
    }
    
    private void resetColor(JPanel panel){
        panel.setBackground(new Color(254, 157, 198));
    }
    
    private void tutupFormEksis(){
        JInternalFrame[] internal=DesktopPane.getAllFrames();
        if(internal!=null){
            for(int i=0; i<internal.length;i++){
                internal[i].dispose();
            }
        }
    }
    
    public JPanel btnUser(){
        return btnUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnBuku = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAnggota = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnTransaksi = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnUser = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLaporan = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        btnBeranda = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        DesktopPane = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        panelBg.setBackground(new java.awt.Color(255, 255, 255));
        panelBg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBgMouseDragged(evt);
            }
        });
        panelBg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBgMousePressed(evt);
            }
        });
        panelBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 97, 150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuku.setBackground(new java.awt.Color(254, 157, 198));
        btnBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBukuMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Buku");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Book_25px.png"))); // NOI18N

        javax.swing.GroupLayout btnBukuLayout = new javax.swing.GroupLayout(btnBuku);
        btnBuku.setLayout(btnBukuLayout);
        btnBukuLayout.setHorizontalGroup(
            btnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        btnBukuLayout.setVerticalGroup(
            btnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel1.add(btnBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 50));

        btnAnggota.setBackground(new java.awt.Color(254, 157, 198));
        btnAnggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAnggotaMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Anggota");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Member_25px.png"))); // NOI18N

        javax.swing.GroupLayout btnAnggotaLayout = new javax.swing.GroupLayout(btnAnggota);
        btnAnggota.setLayout(btnAnggotaLayout);
        btnAnggotaLayout.setHorizontalGroup(
            btnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAnggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        btnAnggotaLayout.setVerticalGroup(
            btnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAnggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(btnAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 50));

        btnTransaksi.setBackground(new java.awt.Color(254, 157, 198));
        btnTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTransaksiMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Transaksi");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Purchase Order_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnTransaksiLayout = new javax.swing.GroupLayout(btnTransaksi);
        btnTransaksi.setLayout(btnTransaksiLayout);
        btnTransaksiLayout.setHorizontalGroup(
            btnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        btnTransaksiLayout.setVerticalGroup(
            btnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 50));

        btnUser.setBackground(new java.awt.Color(254, 157, 198));
        btnUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUserMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("User");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Male User_25px.png"))); // NOI18N

        javax.swing.GroupLayout btnUserLayout = new javax.swing.GroupLayout(btnUser);
        btnUser.setLayout(btnUserLayout);
        btnUserLayout.setHorizontalGroup(
            btnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        btnUserLayout.setVerticalGroup(
            btnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 230, 50));

        btnLogout.setBackground(new java.awt.Color(254, 157, 198));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogoutMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Log Out");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sign Out_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnLogoutLayout = new javax.swing.GroupLayout(btnLogout);
        btnLogout.setLayout(btnLogoutLayout);
        btnLogoutLayout.setHorizontalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        btnLogoutLayout.setVerticalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 230, 50));

        btnLaporan.setBackground(new java.awt.Color(254, 157, 198));
        btnLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLaporanMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Laporan");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Report Card_25px.png"))); // NOI18N

        javax.swing.GroupLayout btnLaporanLayout = new javax.swing.GroupLayout(btnLaporan);
        btnLaporan.setLayout(btnLaporanLayout);
        btnLaporanLayout.setHorizontalGroup(
            btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        btnLaporanLayout.setVerticalGroup(
            btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(btnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 230, 50));

        jSeparator1.setBackground(new java.awt.Color(255, 201, 201));
        jSeparator1.setForeground(new java.awt.Color(255, 201, 201));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 30, 10));

        jLabel14.setBackground(new java.awt.Color(255, 201, 201));
        jLabel14.setFont(new java.awt.Font("Minnie", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 106));
        jLabel14.setText("BeeBook");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        btnBeranda.setBackground(new java.awt.Color(255, 201, 201));
        btnBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBerandaMousePressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Beranda");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Menu_25px.png"))); // NOI18N

        javax.swing.GroupLayout btnBerandaLayout = new javax.swing.GroupLayout(btnBeranda);
        btnBeranda.setLayout(btnBerandaLayout);
        btnBerandaLayout.setHorizontalGroup(
            btnBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBerandaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        btnBerandaLayout.setVerticalGroup(
            btnBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBerandaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(btnBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 230, 50));

        labelNama.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelNama.setForeground(new java.awt.Color(51, 51, 51));
        labelNama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Beebook-30px.png"))); // NOI18N
        jPanel1.add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, 30));

        panelBg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 600));

        DesktopPane.setBackground(new java.awt.Color(153, 255, 255));
        DesktopPane.setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/People_99px.png"))); // NOI18N
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel19MousePressed(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Buku");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Books_99px.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel21MousePressed(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Anggota");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Receipt_99px_2.png"))); // NOI18N
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel23MousePressed(evt);
            }
        });
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Transaksi");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Selamat Datang Di Beebook");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 520, 10));

        DesktopPane.add(jPanel2, "card2");

        panelBg.add(DesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 970, 570));

        jLabel13.setBackground(new java.awt.Color(225, 51, 102));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("X");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        panelBg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 40, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Hai,");
        panelBg.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 30));

        label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        label.setForeground(new java.awt.Color(51, 51, 51));
        label.setText("Nama");
        panelBg.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, 30));

        getContentPane().add(panelBg, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelBgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBgMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_panelBgMousePressed

    private void panelBgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x -xx, y -xy);
    }//GEN-LAST:event_panelBgMouseDragged

    private void btnAnggotaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnggotaMousePressed
        resetColor(btnBuku);
        setColor(btnAnggota);
        resetColor(btnTransaksi);
        resetColor(btnLaporan);
        resetColor(btnUser);
        resetColor(btnLogout);
        resetColor(btnBeranda);
        tutupFormEksis();
        FormAnggota fa=new FormAnggota();
        showForm(fa);
    }//GEN-LAST:event_btnAnggotaMousePressed

    private void btnTransaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMousePressed
        resetColor(btnBuku);
        resetColor(btnAnggota);
        setColor(btnTransaksi);
        resetColor(btnLaporan);
        resetColor(btnUser);
        resetColor(btnLogout);
        resetColor(btnBeranda);
        tutupFormEksis();
        FormTransaksi FT=new FormTransaksi();
        showForm(FT);
    }//GEN-LAST:event_btnTransaksiMousePressed

    private void btnLaporanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMousePressed
        resetColor(btnBuku);
        resetColor(btnAnggota);
        resetColor(btnTransaksi);
        setColor(btnLaporan);
        resetColor(btnUser);
        resetColor(btnLogout);
        resetColor(btnBeranda);
        tutupFormEksis();
        FormLaporan FL=new FormLaporan();
        showForm(FL);
    }//GEN-LAST:event_btnLaporanMousePressed

    private void btnUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMousePressed
        resetColor(btnBuku);
        resetColor(btnAnggota);
        resetColor(btnTransaksi);
        resetColor(btnLaporan);
        setColor(btnUser);
        resetColor(btnLogout);
        resetColor(btnBeranda);
        tutupFormEksis();
        FormUser fu=new FormUser();
        showForm(fu);
        
    }//GEN-LAST:event_btnUserMousePressed

    private void btnLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMousePressed
        resetColor(btnBuku);
        resetColor(btnAnggota);
        resetColor(btnTransaksi);
        resetColor(btnLaporan);
        resetColor(btnUser);
        setColor(btnLogout);
        resetColor(btnBeranda);
        tutupFormEksis();
        FormLogin FL=new FormLogin();
        FL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutMousePressed

    private void btnBukuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBukuMousePressed
        setColor(btnBuku);
        resetColor(btnAnggota);
        resetColor(btnTransaksi);
        resetColor(btnLaporan);
        resetColor(btnUser);
        resetColor(btnLogout);
        resetColor(btnBeranda);
        tutupFormEksis();
        FormBuku fb=new FormBuku();
        showForm(fb);
    }//GEN-LAST:event_btnBukuMousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel13MousePressed

    private void btnBerandaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMousePressed
        resetColor(btnBuku);
        resetColor(btnAnggota);
        resetColor(btnTransaksi);
        resetColor(btnLaporan);
        resetColor(btnUser);
        resetColor(btnLogout);
        setColor(btnBeranda);
        tutupFormEksis();
    }//GEN-LAST:event_btnBerandaMousePressed

    private void jLabel21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MousePressed
        btnBukuMousePressed(evt);
    }//GEN-LAST:event_jLabel21MousePressed

    private void jLabel19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MousePressed
        btnAnggotaMousePressed(evt);
    }//GEN-LAST:event_jLabel19MousePressed

    private void jLabel23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MousePressed
        btnTransaksiMousePressed(evt);
    }//GEN-LAST:event_jLabel23MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new FormUtama(this.toString()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JPanel btnAnggota;
    private javax.swing.JPanel btnBeranda;
    private javax.swing.JPanel btnBuku;
    private javax.swing.JPanel btnLaporan;
    private javax.swing.JPanel btnLogout;
    private javax.swing.JPanel btnTransaksi;
    private javax.swing.JPanel btnUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label;
    private javax.swing.JLabel labelNama;
    private javax.swing.JPanel panelBg;
    // End of variables declaration//GEN-END:variables

    NavigatorFormInt nav;
    public void showForm(Object obj){
        JInternalFrame jf = null;
        jf =(JInternalFrame) obj;
        DesktopPane.add(jf);
        jf.setVisible(true);
        try{
            jf.setMaximum(true);
            jf.setSelected(true);
        }catch(java.beans.PropertyVetoException e){}
    }
}
